# Generated by Django 2.2.16 on 2023-06-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230628_1932'),
        ('reviews', '0002_auto_20230628_2211'),
    ]

    operations = [
    ]
