# Generated by Django 2.2.16 on 2023-07-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230705_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('slug',), 'verbose_name': 'Жанры', 'verbose_name_plural': 'Жанры'},
        ),
    ]
