# Generated by Django 2.2.16 on 2023-07-05 16:14

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20230705_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[api.validators.validate_slug], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[api.validators.validate_slug], verbose_name='Слаг'),
        ),
    ]
